## Section A: Data Structures & Control Structures

### A1) List operations

In [1]:
# LIST OPERATIONS

# Creating list of 5 integers
nums = [10, 20, 30, 40, 50]

# append
nums.append(60)

# extend
nums.extend([70, 80])

# insert at index 2
nums.insert(2, 25)

# remove value
nums.remove(40)

# pop last element
popped = nums.pop()

# index of 30
index_30 = nums.index(30)

# count occurrences
count_20 = nums.count(20)

# sort list
nums.sort()

# reverse list
nums.reverse()

print("Final List:", nums)
print("Popped:", popped)
print("Index of 30:", index_30)
print("Count of 20:", count_20)

Final List: [70, 60, 50, 30, 25, 20, 10]
Popped: 80
Index of 30: 3
Count of 20: 1


### A2) Tuple immutability

In [2]:
# TUPLE IMMUTABILITY

students = ("Aman", "Rahul", "Neha")

try:
    # Attempt to modify (will raise TypeError because tuples are immutable)
    students[1] = "Rohit"
except TypeError as e:
    print("Error:", e)
    print("Explanation: Tuples are immutable, so you cannot change their elements after creation.")

Error: 'tuple' object does not support item assignment
Explanation: Tuples are immutable, so you cannot change their elements after creation.


### A3) Set with duplicates

In [3]:
# SET REMOVES DUPLICATES

s = {1, 2, 2, 3, 4, 4, 5}
print("Set contents (duplicates removed):", s)
print("Explanation: Sets store only unique values, so duplicates are removed automatically.")

Set contents (duplicates removed): {1, 2, 3, 4, 5}
Explanation: Sets store only unique values, so duplicates are removed automatically.


### A4) Dictionary update

In [4]:
# DICTIONARY UPDATE

person = {"name": "John", "age": 25, "city": "Mumbai"}
person["age"] = 26              # update existing key
person["email"] = "john@example.com"  # add new key
print("Updated dictionary:", person)

Updated dictionary: {'name': 'John', 'age': 26, 'city': 'Mumbai', 'email': 'john@example.com'}


### A5) Voting eligibility (age ≥ 18)

In [5]:
# VOTING ELIGIBILITY

def voting_eligibility(age):
    """Return eligibility message for voting based on age."""
    if age >= 18:
        return "Eligible to vote"
    else:
        return "Not eligible to vote"

# Example
age_example = 17
print(f"Age {age_example}: {voting_eligibility(age_example)}")

Age 17: Not eligible to vote


### A6) Grade from marks

In [6]:
# GRADE CALCULATION

def grade_from_marks(marks):
    """Return grade based on marks."""
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"

# Example
marks_example = 82
print(f"Marks {marks_example}: Grade {grade_from_marks(marks_example)}")

Marks 82: Grade B


### A7) Check if number is positive, and if positive, whether it is even

In [7]:
# POSITIVE / EVEN CHECK

def positive_even_check(num):
    """Print relationship of num to zero and parity if positive."""
    if num > 0:
        if num % 2 == 0:
            return "Positive and even"
        else:
            return "Positive but odd"
    elif num == 0:
        return "Zero"
    else:
        return "Negative"

# Example
num_example = 12
print(f"{num_example}: {positive_even_check(num_example)}")

12: Positive and even


## Section B: Numpy

### B1) Create scalar, 1D, and 2D arrays

In [8]:
# CREATE ARRAYS

import numpy as np
import pandas as pd

# Scalar
scalar = np.array(5)
print("Scalar:", scalar, "| shape:", np.shape(scalar))

# 1D array 1..5
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

# 2D array (2x3) with values 10..60 step 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D array:\n", arr_2d)

Scalar: 5 | shape: ()
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


### B2) 4×4 random integers (0–100)

In [9]:
# RANDOM 4x4 ARRAY

rand_arr = np.random.randint(0, 100, (4, 4))
rand_arr

array([[ 8, 95, 27, 95],
       [40,  8, 24, 20],
       [32,  3, 40, 60],
       [80, 95, 79, 59]])

### B3) 3×3 array → DataFrame with columns A, B, C

In [10]:
# NUMPY ARRAY TO PANDAS DATAFRAME

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

df_from_arr = pd.DataFrame(arr, columns=['A', 'B', 'C'])
df_from_arr

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Section C: Exploring Pandas

### C1) Create DataFrame with 10 rows: Name, Age, City, Salary

In [11]:
# CREATE SAMPLE DATAFRAME (with one missing Salary and a duplicate row)

data = {
    'Name':  ['A','B','C','D','E','F','G','H','I','J'],
    'Age':   [23,25,22,30,28,25,29,22,23,26],
    'City':  ['Mumbai','Delhi','Mumbai','Pune','Delhi','Pune','Mumbai','Delhi','Pune','Delhi'],
    'Salary':[50000,60000,55000,65000,None,53000,57000,60000,55000,65000]
}
df = pd.DataFrame(data)

# Add a deliberate duplicate to demonstrate duplicate removal later
df = pd.concat([df, df.iloc[[1]]], ignore_index=True)

df

Name  Age    City   Salary
0     A   23  Mumbai  50000.0
1     B   25   Delhi  60000.0
2     C   22  Mumbai  55000.0
3     D   30    Pune  65000.0
4     E   28   Delhi      NaN
5     F   25    Pune  53000.0
6     G   29  Mumbai  57000.0
7     H   22   Delhi  60000.0
8     I   23    Pune  55000.0
9     J   26   Delhi  65000.0
10    B   25   Delhi  60000.0

### C2) `.info()` and `.describe()`

In [12]:
# DATAFRAME INFO AND DESCRIBE

print("DataFrame info():")
df.info()
print("\nDataFrame describe():")
df.describe()

DataFrame info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 484.0+ bytes

DataFrame describe():


Age        Salary
count  11.000000     10.000000
mean   25.272727  58000.000000
std     2.760105   4921.607687
min    22.000000  50000.000000
25%    23.000000  55000.000000
50%    25.000000  58500.000000
75%    27.000000  60000.000000
max    30.000000  65000.000000

### C3) Select 'Name' and 'City' columns

In [13]:
# SELECT COLUMNS

df[['Name','City']]

Name    City
0     A  Mumbai
1     B   Delhi
2     C  Mumbai
3     D    Pune
4     E   Delhi
5     F    Pune
6     G  Mumbai
7     H   Delhi
8     I    Pune
9     J   Delhi
10    B   Delhi

### C4) Drop 'City' column

In [14]:
# DROP COLUMN

df_dropped_city = df.drop(columns=['City'])
df_dropped_city.head(12)

Name  Age   Salary
0     A   23  50000.0
1     B   25  60000.0
2     C   22  55000.0
3     D   30  65000.0
4     E   28      NaN
5     F   25  53000.0
6     G   29  57000.0
7     H   22  60000.0
8     I   23  55000.0
9     J   26  65000.0
10    B   25  60000.0

### C5) Fill missing Salary with mean

In [15]:
# FILL MISSING VALUES WITH MEAN

salary_mean = df['Salary'].mean()
df_filled = df.copy()
df_filled['Salary'] = df_filled['Salary'].fillna(salary_mean)
print("Salary mean used for fillna:", salary_mean)
df_filled.head(12)

Salary mean used for fillna: 58000.0


Name  Age    City   Salary
0     A   23  Mumbai  50000.0
1     B   25   Delhi  60000.0
2     C   22  Mumbai  55000.0
3     D   30    Pune  65000.0
4     E   28   Delhi  58000.0
5     F   25    Pune  53000.0
6     G   29  Mumbai  57000.0
7     H   22   Delhi  60000.0
8     I   23    Pune  55000.0
9     J   26   Delhi  65000.0
10    B   25   Delhi  60000.0

### C6) Remove duplicate rows

In [16]:
# REMOVE DUPLICATES

df_no_dupes = df_filled.drop_duplicates()
df_no_dupes

Name  Age    City   Salary
0    A   23  Mumbai  50000.0
1    B   25   Delhi  60000.0
2    C   22  Mumbai  55000.0
3    D   30    Pune  65000.0
4    E   28   Delhi  58000.0
5    F   25    Pune  53000.0
6    G   29  Mumbai  57000.0
7    H   22   Delhi  60000.0
8    I   23    Pune  55000.0
9    J   26   Delhi  65000.0